version: "3.9"
services:
  backend:
    build:
      context: ./backend
    image: tg-ai-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-1000}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
    image: tg-ai-frontend:latest
    environment:
      - VITE_API_BASE_URL=/api
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_data:
