services:
  backend:
    build:
      context: ./backend
    image: tg-ai-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-1000}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CORS_ORIGIN=https://24ablyakimov.ru
    networks:
      - app-network
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
    image: tg-ai-frontend:latest
    environment:
      - VITE_API_BASE_URL=/api
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
