module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.spec.ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  verbose: false,
  silent: false,
  testTimeout: 3000,
  maxWorkers: 1,
  forceExit: true,
  detectOpenHandles: false,
  clearMocks: true,
  restoreMocks: true,
  watchman: false,
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
};